server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: ai_agency
    basic_auth:
      username: admin
      password: admin_prod_2024

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<level>\w+) (?P<message>.*)'
      - labels:
          level:
          timestamp:

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: time
      - labels:
          level:
          timestamp:

  - job_name: ai_agency_services
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai_agency
          service: auth
          __path__: /var/log/ai_agency/auth/*.log
      - targets:
          - localhost
        labels:
          job: ai_agency
          service: ai_orchestrator
          __path__: /var/log/ai_agency/ai_orchestrator/*.log
      - targets:
          - localhost
        labels:
          job: ai_agency
          service: template
          __path__: /var/log/ai_agency/template/*.log
      - targets:
          - localhost
        labels:
          job: ai_agency
          service: monitoring
          __path__: /var/log/ai_agency/monitoring/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: time
            trace_id: trace_id
            user_id: user_id
            request_id: request_id
      - labels:
          level:
          trace_id:
          user_id:
          request_id: 