global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus/rules/deploy-alerts.yml"
  - "prometheus/rules/continuous-monitoring.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'backend'
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 