version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus_prod
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=50GB'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "65534:65534"  # nobody:nogroup
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager_prod
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    networks:
      - monitoring_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "65534:65534"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  node_exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node_exporter_prod
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "65534:65534"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor_prod
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    networks:
      - monitoring_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  prometheus_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  monitoring_net:
    driver: bridge 