global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8000']

  - job_name: 'ai_orchestrator'
    static_configs:
      - targets: ['ai_orchestrator:8001']

  - job_name: 'template_service'
    static_configs:
      - targets: ['template_service:8002']

  - job_name: 'monitoring_service'
    static_configs:
      - targets: ['monitoring_service:8003']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] 