apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin_prod_2024
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: trace_id
          matcherRegex: "trace_id=(\\w+)"
          url: "${__value.raw}"
          datasourceUid: tempo
    editable: false
    version: 1 