apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://prometheus.prod:9090
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin_prod_2024
      httpHeaderValue1: "Bearer ${GRAFANA_API_KEY}"
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: "POST"
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.45.0"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    editable: false
    version: 1 