version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana_prod
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://grafana.prod
      - GF_SERVER_DOMAIN=grafana.prod
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=strict
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=info
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "472:472"  # grafana:grafana
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  grafana_data:
    driver: local

networks:
  monitoring_net:
    external: true 