global:
  resolve_timeout: 5m
  smtp_from: '{{ settings.SMTP_FROM_EMAIL }}'
  smtp_smarthost: '{{ settings.SMTP_HOST }}:{{ settings.SMTP_PORT }}'
  smtp_auth_username: '{{ settings.SMTP_USER }}'
  smtp_auth_password: '{{ settings.SMTP_PASSWORD }}'
  smtp_require_tls: {{ settings.SMTP_TLS }}

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'security-team'
  routes:
    - match:
        severity: critical
      receiver: 'security-team-critical'
      group_wait: 0s
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'security-team-warnings'

receivers:
  - name: 'security-team'
    email_configs:
      - to: '{{ settings.AUDIT_ALERT_EMAIL }}'
        send_resolved: true
    slack_configs:
      - api_url: '{{ settings.SLACK_WEBHOOK_URL }}'
        channel: '#security-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'

  - name: 'security-team-critical'
    email_configs:
      - to: '{{ settings.AUDIT_ALERT_EMAIL }}'
        send_resolved: true
    slack_configs:
      - api_url: '{{ settings.SLACK_WEBHOOK_URL }}'
        channel: '#security-critical'
        send_resolved: true
        title: '[CRITICAL] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'

  - name: 'security-team-warnings'
    email_configs:
      - to: '{{ settings.AUDIT_ALERT_EMAIL }}'
        send_resolved: true
    slack_configs:
      - api_url: '{{ settings.SLACK_WEBHOOK_URL }}'
        channel: '#security-warnings'
        send_resolved: true
        title: '[WARNING] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'

templates:
  - name: 'slack.default.title'
    template: '{{ .GroupLabels.alertname }}'
  - name: 'slack.default.text'
    template: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Started:* {{ .StartsAt }}
      {{ if .EndsAt }}*Ended:* {{ .EndsAt }}{{ end }}
      {{ end }}
  - name: 'slack.default.footer'
    template: 'AI Agency Security Monitoring'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname'] 