groups:
  - name: api_metrics
    rules:
      - record: job:http_requests_total:rate5m
        expr: rate(http_requests_total[5m])

      - record: job:http_request_duration_seconds:avg5m
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])

      - record: job:http_request_duration_seconds:p95_5m
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))

      - record: job:error_rate:ratio5m
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])

  - name: resource_metrics
    rules:
      - record: job:process_cpu_usage:avg5m
        expr: rate(process_cpu_seconds_total[5m]) * 100

      - record: job:process_memory_usage:ratio
        expr: process_resident_memory_bytes / node_memory_MemTotal_bytes * 100

      - record: job:node_cpu_usage:avg5m
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

  - name: openai_metrics
    rules:
      - record: job:openai_requests:rate5m
        expr: rate(openai_requests_total[5m])

      - record: job:openai_request_duration:avg5m
        expr: rate(openai_request_duration_seconds_sum[5m]) / rate(openai_request_duration_seconds_count[5m])

      - record: job:openai_error_rate:ratio5m
        expr: rate(openai_requests_total{status="error"}[5m]) / rate(openai_requests_total[5m])

      - record: job:openai_token_usage:ratio
        expr: openai_token_quota_remaining / openai_token_quota_total * 100 