global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'deploy-metrics'
    honor_labels: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']
    metric_relabel_configs:
      - source_labels: [job]
        regex: 'deploy'
        action: keep

# Regras de alerta específicas para deploy
rule_files:
  - "rules/deploy-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 